all:
  hosts:
    k8s-node-1:
      ansible_host: 10.148.0.18
      ip: 10.148.0.18
      access_ip: 10.148.0.18
    k8s-node-2:
      ansible_host: 10.148.0.26
      ip: 10.148.0.26
      access_ip: 10.148.0.26
    k8s-node-3:
      ansible_host: 10.148.0.29
      ip: 10.148.0.29
      access_ip: 10.148.0.29
  children:
    kube-master:
      hosts:
        k8s-node-1:
    kube-node:
      hosts:
        k8s-node-1:
        k8s-node-2:
        k8s-node-3:
    etcd:
      hosts:
        k8s-node-1:
        k8s-node-2:
        k8s-node-3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
